### ISSUE TITLE
Image is cut in width

### ISSUE THREAD

**Issue by alexteusz** [frinyvonnick/node-html-to-image-cli#2] opened 2020-11-11 15:58 UTC
Hey @frinyvonnick ,

First, the tool is very easy to use, thanks. However, my used HTML is cut in width and I do not know why since it is displayed right as HTML website.

General CSS:

- Width: 1200px
- Height: 627px

Is there a maximum of pixel for width or why is it cut? Could you help me with this?

Best
Alex

**Comment by frinyvonnick** [comment] 2020-11-12 07:47
Hi @AlexTeusz 👋 

Can you share your HTML so I try to reproduce your issue. There is not any limit in term of size.

**Comment by alexteusz** [comment] 2020-11-12 07:50
Good morning from Germany,

The HTML is highly branded with information which I cannot share here in public :D. Would you mind jumping on a call with me later this day or this week?

Thanks @frinyvonnick 
Alex

**Comment by frinyvonnick** [comment] 2020-11-12 08:01
Maybe you could create a example that reproduce your issue and remove all branded information from it so you could share it?

Sorry I'm starting a new job I won't have to much free time in the next few weeks 😄

**Comment by alexteusz** [comment] 2020-11-12 08:31
Congrats! Yes, I will create a nice white labeled version  :) 

@frinyvonnick do you have an email I can send this to?

Best
Alex

**Comment by frinyvonnick** [comment] 2020-11-12 11:49
I prefer to keep things public so it could help someone as well so post it directly here. Since it will be white labeled It won't be a problem I guess 👍

**Comment by alexteusz** [comment] 2020-11-12 11:57
@frinyvonnick : Here is the HTML:

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Example File</title>
    <link rel="stylesheet" href="https://alexteusz.s3-eu-west-1.amazonaws.com/cognigy/academy/certificates/layout.css">
    <!-- <link rel="stylesheet" href="./linkedincertificate.css"> -->
    <link rel="stylesheet" href="https://alexteusz.s3-eu-west-1.amazonaws.com/cognigy/academy/certificates/linkedincertificate.css">
    <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@300;400;500;600;700;800;900&display=swap"
        rel="stylesheet">
</head>

<body>
    <div class="certificate-container">
        <div class="certificate-02">
            <div class="row-fluid">
                <div class="span12 wrapper">
                    <div class="certificate-content">
                        <div class="align-center">
                            <div class="logo-container">
                                
                            </div>
                            <div class="top-section">
                                <h1>File</h1>
                                <h4>SUBTITLE</h4>
                            </div>
                            <div class="middle-section">
                                <h6>LOREM IPSUM BLUB</h6>
                                <h2>%var%</h2>
                                <h6>LATIN TEXT PLACEHOLDER</h6>
                                <h2>%var%</h2>
                            </div>
                            <div class="bottom-section">
                                <!-- <div class="span12 equal-height-container"> -->
                                <!-- <div class="row-fluid-wrapper"> -->
                                    <!-- <div class="row-fluid"> -->
                                    <div class="span4 sub-container-1 vertical-center">
                                        <h6>Issued on</h6>
                                        <h6 style="font-weight: 700;">%var%</h6>
                                    </div>
                                    <div class="span4 sub-container-2 align-center vertical-center">
                                       
                                        <h6>Peter Pan</h6>
                                        <h6>My Company</h6>
                                    </div>
                                    <div class="span4 sub-container-3 vertical-center align-right">
                                        <h6>© 2020 Company</h6>
                                    </div>
                                    <!-- </div> -->
                                </div>
                                <!-- </div> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>
```

**Comment by alexteusz** [comment] 2020-11-17 08:53
@frinyvonnick Did you already have time to take a look at it? Thanks

**Comment by frinyvonnick** [comment] 2020-11-17 13:17
Hi @AlexTeusz 👋 

Adding this style in the head tag fixes your issue.

```html
    <style>
      body {
        width: 1240px;
        height: 667px;
      }
    </style>
```

As explained in the node-html-to-image's [README](https://github.com/frinyvonnick/node-html-to-image#setting-output-image-resolution) you have to set the body size to fit your target resolution 👍 

Please close this issue if the provided solution fixes your problem 😄

**Comment by alexteusz** [comment] 2020-11-17 15:24
Oh thank you so much :D

**Closed as completed** 2020-11-17 15:25 UTC
